### ISSUE TITLE
<script> tag within .vue file does not support src attribute

### ISSUE THREAD

**Issue by mistyharsh** [vuejs/rollup-plugin-vue#100]
### Expected behavior
This should work:
```vue
// file: checkbox.vue
<template>
    <div class="mdc-form-field"> </div>
</template>

<script src="./checkbox.js"></script>
```

### Actual behavior
Compiling the vue file failed with these words:
`
(vue plugin) [rollup-plugin-vue] Generated render function is injected in the default export of .vue file (lang: js). In /home/harshal/personal/vue-toolkit/src/checkbox/checkbox.vue, it cannot find 'export defaults'.
`

### Steps to reproduce the behavior
I believe `<script>` tags in `.vue` files do not support `src` attribute.

**Comment by znck** [comment]
This is not supported as of now.

**Comment by sunnylost** [comment]
```javascript
if (source.attrs.src) {
    source.code = `import __vue__module__ from '${source.attrs.src}'; export default __vue_module__;`
}
```

is this ok? what else should consider? :confused:
