### ISSUE TITLE
Autoprefixer support

### ISSUE THREAD

**Issue by yunyu** [vuejs/rollup-plugin-vue#102]
Currently, only cssModules is exposed in the configuration, making it impossible to add things like autoprefixer (since that's done at a higher level config object).

**Comment by znck** [comment]
You can provide options for style compilers. For sass - https://github.com/vuejs/rollup-plugin-vue/blob/master/src/style/scss.js#L12 similarly for other languages too.

**Comment by yunyu** [comment]
Nope, turns out it was the "Use other plugins" section.
