### ISSUE TITLE
Component style missing after tree-shaking 

### ISSUE THREAD

**Issue by krimeshu** [vuejs/rollup-plugin-vue#104]
`hello.vue`:
```html
<template>
    <div class="container">
        <p v-for="item in list" :data-total="total">
            {{item}}
        </p>    
    </div>
</template>

<script>
export default {
    data: function () {
        return {
            list: ['hello', 'world'],
            total: 123
        }
    }
}
</script>

<style scoped>
.container {
    background: #eff;
}
</style>
```

`entry.js`:
```javascript
import hello from './hello.vue';

new Vue({
    el: '#vueApp',
    components: { hello },
    template: `
        <hello/>
    `
})
```

### Expected behavior

Compile .vue to .js, contains style parts.

### Actual behavior

Generated .js doesn't contains style parts.

```javascript
var hello = { render: function render() {
        var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "container" }, _vm._l(_vm.list, function (item) {
            return _c('p', { attrs: { "data-total": _vm.total } }, [_vm._v(_vm._s(item))]);
        }));
    }, staticRenderFns: [], _scopeId: 'data-v-9d9be692',
    data: function data() {
        return {
            list: ['hello', 'world'],
            total: 123
        };
    }
};

new vue$1({
    el: '#vueApp',
    components: { hello: hello },
    template: '\n        <hello/>\n    '
});

```

### Steps to reproduce the behavior

Use `gulp-better-rollup` with `rollup-plugin-vue` to compile `entry.js`.

**Comment by krimeshu** [comment]
Is the style parts removed by rollup tree-shaking? How to prevent it?

**Comment by krimeshu** [comment]
Oh, the style generated into another .css file, not like what vueify do (join into the .js file), got it.

**Comment by znck** [comment]
Set `css: true` to dynamically inject css in js.

**Comment by krimeshu** [comment]
Yes, with `css: true` I got the expected behavior.

By the way, can I use `autoprefixer` to process the css, and then inject it into js?

It seems that `css: function () { ...` can only write css into individual file, can't return the processed css and inject it into js.

**Comment by znck** [comment]
Create a feature request, this could be useful.
