### ISSUE TITLE
Doesn't compile CSS of all .vue files on repeated (in memory) invocation

### ISSUE THREAD

**Issue by duzun** [vuejs/rollup-plugin-vue#106]
I use `browserSync` and `rollup` in a `gulp live` command to watch for file changes and compile JS automatically. My JS imports a bunch of `.vue` files and `rollup-plugin-vue` is collectiong all CSS from all components in `vue/vue.css` file.
On first run everything is good.

### Expected behavior
It should gather all CSS from all `.vue` components in one `vue/vue.css` file on each run inside a persistent process.

### Actual behavior
On the second and consequent runs inside the same process, it collects CSS from only one `.vue` component.

### Steps to reproduce the behavior
I run `gulp-better-rollup` with the following plugins:

```js
   let plugins = [
        // require('rollup-plugin-strip')(),
        require('rollup-plugin-json')(),
        require('rollup-plugin-node-resolve')({
            jsnext: true,
            main: true
        }),
        require('rollup-plugin-commonjs')({
            extensions: [ '.js', '.json', '.vue' ],
            namedExports: {
                'perfect-scrollbar': ['initialize', 'update', 'destroy'],
            }
        }),
        require('rollup-plugin-vue')({
            css: './vue/vue.css'
        }),
        require('rollup-plugin-babel')(bo),
    ];
```
multiple time inside the same process for the same source files.

**Comment by znck** [comment]
I want to support incremental/subsequent builds. I would be doing this early next month. If anyone want to pick up, you're most welcome.

Related #67
