### ISSUE TITLE
Compiling for production usage

### ISSUE THREAD

**Issue by benjarwar** [vuejs/rollup-plugin-vue#107]
### Expected behavior
Following the [Vue docs](https://vuejs.org/v2/guide/deployment.html#With-Build-Tools), I should be able to use [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace) to compile my Vue files in production mode.

### Actual behavior
After compilation, still receiving the following message in my browser console:

```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

### Steps to reproduce the behavior
My actual config is using [rollup-stream](https://github.com/Permutatrix/rollup-stream), so I can combine some Gulp processes. But I've eliminated that and used a standard `rollup.config.js` like so:

```
import vue from 'rollup-plugin-vue';
import babel from 'rollup-plugin-buble';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import replace from 'rollup-plugin-replace';

export default {
  entry: './src/js/app.js',
  dest: './dist/app.js',
  format: 'iife',
  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify('production')
    }),
    resolve({
      jsnext: true,
      main: true,
      browser: true,
    }),
    commonjs(),
    vue({compileTemplate: true}),
    babel(),
  ],
};
```

And the compiled JS still seems to be stuck in development mode.

**Comment by znck** [comment]
I suppose putting `vue` first in plugin list would work.

> P.S.: I'll try/test and get back.

**Comment by benjarwar** [comment]
@znck figured out the issue. The `dist` version Vue was being imported in another component like so:

```
import Vue from 'vue/dist/vue.js';
```

That version has `develop` instead of `process.env.NODE_ENV` in the conditional logic and config, so my `replace` was getting overridden. Oof; sorry to bother you!
