### ISSUE TITLE
Use AST insteadof RegExp to inject code

### ISSUE THREAD

**Issue by Jack-Works** [vuejs/rollup-plugin-vue#110]
Regexp is really easy to break.
Parse script like AST will make it easier to modify.
As an example, findInjectionPosition(script) will have wrong behavior in code like
```JS
var code = `export default {}`
// then code will be inject ^ here
```

**Comment by Jack-Works** [comment]
Since typescript is already used in this project, I think the parser of ts may be useful

**Comment by znck** [comment]
Using a runtime helper same as vue-loader.
