### ISSUE TITLE
Consider enabling `htmlMinifier.conservativeCollapse` by default

### ISSUE THREAD

**Issue by mrkishi** [vuejs/rollup-plugin-vue#116]
I was quite surprised to find out `html-minifier`'s `collapseWhitespace` option is turned on, by default, without `conservativeCollapse`.

`vue-html-loader`, for instance, sets both to true.

Is this intentional or an oversight?

**Comment by znck** [comment]
It converts template to render function by default. Most commonly this plugin has been used for UI kits or plugins, keeping string template does not make sense here. I think it should strictly compile to render function for non-iife builds. 

You can send a PR. This was not intentional.

**Comment by mrkishi** [comment]
I'm using it to compile to a render function, but it uses `html-minifier` to preprocess the template prior to passing it to `vue-template-compiler`.

This caught me so much off-guard that I was actually trying to find the minification in `vue-template-compiler` at first, heh.

**Comment by znck** [comment]
I'll look into it.

**Comment by mrkishi** [comment]
Changing this introduces too many `_v(" ")` to the output. And while I think it's safer, it'd be a breaking change.

 Ideally, `html-minifier` would support customizing which tags it preserves white-space around. For `vue`, it's slightly cumbersome because it doesn't consider `template` tags inline:

```html
Some <template v-if="a">{{a}}</template><template v-else-if="b">{{b}}</template> here!
```

becomes effectively:

```html
Some<template v-if="a">{{a}}</template><template v-else-if="b">{{b}}</template>here!
```

This also happens to other tags such as `output`.

I'm inclined to take this to `html-minifier` instead. Do you know if every _phrasing content_ tag is considered inline? Because [it looks like that's the case](http://jsbin.com/pexevodesu/edit?html,output), yet their inline tags list doesn't include all of them.

**Comment by znck** [comment]
I'd skip html minify step from render function compilation. And have it for string template.
