### ISSUE TITLE
Feature Request: Support PostCSS as vue-loader

### ISSUE THREAD

**Issue by fengyuanchen** [vuejs/rollup-plugin-vue#118]
Check out the [postcss feature](https://vue-loader.vuejs.org/en/features/postcss.html) of **vue-loader** for more detail.

**Comment by whaaaley** [comment]
does postcss not work atm? could these incompatibilities with vueify and vue-loader be documented somewhere?

**Comment by znck** [comment]
Supported in v4. See http://github.com/vuejs/vue-component-compiler for options.
