### ISSUE TITLE
es6 doesnt get transpiled

### ISSUE THREAD

**Issue by BennyAlex** [vuejs/rollup-plugin-vue#121]
### Expected behavior
For example let -> var

### Actual behavior
es6 doesnt get transpiled to simple js

### Steps to reproduce the behavior
I am using babel plugin and vue plugin for rollup.
This is my rollup config:
```
import vue from 'rollup-plugin-vue'
import nodeResolve from 'rollup-plugin-node-resolve'
import replace from 'rollup-plugin-replace'
import uglify from 'rollup-plugin-uglify'
import {minify} from 'uglify-es'
import babel from 'rollup-plugin-babel';

const production = process.env.NODE_ENV === 'production'
if (!production) console.log('Running in development mode.')

export default [
  {
    entry: 'src/main.js',
    dest: 'dist/md-color-picker.js',
    format: 'es',
    plugins: [
      replace({
        'process.env.NODE_ENV': production ? JSON.stringify('production') : JSON.stringify('develop')
      }),
      nodeResolve({
        module: true,
        jsnext: true,
        main: true
      }),
      babel({
        exclude: ['node_modules/**', 'src/components/**']
      }),
      vue({
        compileTemplate: true,
        css: true
      }),
      uglify({}, minify)
    ]
  },
  {
    entry: 'src/main.js',
    dest: 'docs/md-color-picker.js',
    format: 'es',
    plugins: [
      replace({
        'process.env.NODE_ENV': production ? JSON.stringify('production') : JSON.stringify('develop')
      }),
      nodeResolve({
        module: true,
        jsnext: true,
        main: true
      }),
      babel({
        exclude: ['node_modules/**', 'src/components/**']
      }),
      vue({
        compileTemplate: true,
        css: true
      })
    ]
  }
]
```
and my dependencies:
```
"devDependencies": {
    "babel-core": "^6.25.0",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-preset-es2015": "^6.24.1",
    "cross-env": "^5.0.5",
    "rimraf": "^2.6.1",
    "rollup": "^0.47.4",
    "rollup-plugin-babel": "^3.0.2",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-plugin-replace": "^1.1.1",
    "rollup-plugin-uglify": "^2.0.1",
    "rollup-plugin-vue": "^2.4.1",
    "rollup-watch": "^4.3.1",
    "uglify-es": "^3.0.27",
    "vue": "^2.4.2",
    "vue-custom-element": "^1.3.0"
  }
```

**Comment by sunnylost** [comment]
Hi, i think the reason is babel config was not being set correctly. You need to do another two things:
- run `npm i -D babel-plugin-external-helpers`
- create a `.babelrc` file, it's content should like this:
```json
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

**Comment by znck** [comment]
As @sunnylost said, it has do with your babel config. 

Vue plugin keeps your JavaScript as it is.

**Comment by BennyAlex** [comment]
@sunnylost thats what I have already, still not working

**Comment by sunnylost** [comment]
@BennyAlex can you provide a demo?

**Comment by BennyAlex** [comment]
@sunnylost I created a new project and installed every thing again. Now it is working. But in internet explorer I get a wired error:

Symbol is undefinded. Maybe you have a solution?
`
created: function created() {
    var _this2 = this;

    if (!this.value || this.value.length !== 7 || this.selectedColorName) return; // value must be in hex format, eg: #ffffff
    Object.keys(this.currentPalette).forEach(function (key) {
      var valueOrObject = _this2.currentPalette[key];
      var values = typeof valueOrObject === 'string' ? [valueOrObject] : valuesOfObj(valueOrObject);
      var _iteratorNormalCompletion = true;
      var _didIteratorError = false;
      var _iteratorError = undefined;

      try {
        for (var _iterator = values[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
          var value = _step.value;

          if (value === _this2.value) {
            _this2.selectedColorName = name;
            return;
          }
        }
      } catch (err) {
        _didIteratorError = true;
        _iteratorError = err;
      } finally {
        try {
          if (!_iteratorNormalCompletion && _iterator.return) {
            _iterator.return();
          }
        } finally {
          if (_didIteratorError) {
            throw _iteratorError;
          }
        }
      }
    });
  }`

**Comment by sunnylost** [comment]
Which IE version? `Symbol` is a new primitive type, if your ie version is low, you have to polyfill it.

See [https://babeljs.io/docs/usage/polyfill/](https://babeljs.io/docs/usage/polyfill/)

**Comment by BennyAlex** [comment]
@sunnylost IE 11.
But I didnt wrote it, this is the babel output. Any idea why babel is using that symbol?

**Comment by sunnylost** [comment]
[ES2015 for-of transform](https://babeljs.io/docs/plugins/transform-es2015-for-of/), babel will use `Symbol` to transform `for...of`, and IE only support it at Edge, that means IE 12 and above.

So, you need `babel-polyfill`.
