### ISSUE TITLE
`compile` with custom handler

### ISSUE THREAD

**Issue by jonataswalker** [vuejs/rollup-plugin-vue#122]
Hey folks. How do you suppose to use `compile` async function to process css?

My case is similar to #102 and https://github.com/vuejs/rollup-plugin-vue/issues/104#issuecomment-310312816, I need to process css with `autoprefixer`.

**Comment by jonataswalker** [comment]
Maybe some guidance to a PR?

**Comment by sunnylost** [comment]
I was working on a PR to support postcss, maybe tomorrow.

**Comment by jonataswalker** [comment]
For me this can be closed since #125 was merged.

Thanks @sunnylost @znck
