### ISSUE TITLE
Feature Request: Support For Markdown in Templates

### ISSUE THREAD

**Issue by nwpappas** [vuejs/rollup-plugin-vue#127]
Support to use markdown in the template would be helpful for projects in which route pages are very text heavy. I believe the `vue-loader` support markdown, but I'm not totally sure.

```
<template lang="md">
# Feature Request

The following is a feature request for `rollup-plugin-vue`.

## Templates

### Lang

The ability to set the __lang__ attribute to *md* would be great!
</template>
```

**Comment by znck** [comment]
Supports all the template languages handled by `consolidate` package. Fixed in v4.
