### ISSUE TITLE
Respect stylus @require behavior

### ISSUE THREAD

**Issue by WoodyWoodsta** [vuejs/rollup-plugin-vue#130]
### Expected behavior
When requiring a stylus file, via the `@require` statement, in two individual but bundled components, the classes in the stylus file should only appear in the bundle once.

### Actual behavior
The compiled stylus code appears twice (exact duplicates) in the css bundle. This is `@import` behaviour which does not dedupe.

### Steps to reproduce the behavior
Create a stylus file with a style rule. Create two single file components and require the stylus file in un-scoped style tags in each component. The style rule appears twice in the css bundle.

**Comment by znck** [comment]
If this issues persists, it have to be handled on http://github.com/vuejs/component-compiler-utils repo.
