### ISSUE TITLE
Can't import .css file inside Vue component

### ISSUE THREAD

**Issue by EvilClosetMonkey** [vuejs/rollup-plugin-vue#131]
### Expected behavior

The following should import the contents of the `foo.css`.

```html
<style lang="scss">
@import 'foo.css';

.some-more-styles {
...
}
</style>
```

### Actual behavior

`foo.css` is not imported. Renaming `foo.css` to `foo.scss` (and updating `@import` statement) fixes issue.

### Steps to reproduce the behavior

1. Create .vue file with `<style>` tag.
1. Include `@import` statement to `.css` file.
1. Bundle

**Comment by znck** [comment]
Change to this.

```diff
- @import 'foo.css';
+ @import 'foo';
```
