### ISSUE TITLE
Add documentation for #125

### ISSUE THREAD

**Issue by znck** [vuejs/rollup-plugin-vue#134]
@sunnylost Please add documentation for #125

**Comment by sunnylost** [comment]
I’m spending the whole September on a work project, so i maybe don't have enough time to write this, my apologies.

**Comment by sunnylost** [comment]
Holiday comes, got a little break. So where should I write this document? `docs` only contains `2.2` and `2.3`.

**Comment by znck** [comment]
Thanks. In `2.3`, I'll rename it to `2.5`.
