### ISSUE TITLE
v2.5.0 can't find 'vue-template-compiler'

### ISSUE THREAD

**Issue by EvilClosetMonkey** [vuejs/rollup-plugin-vue#135]
### Expected behavior

Compile using Rollup, without getting error.

### Actual behavior

Getting an error:

![screen shot 2017-09-28 at 2 35 39 pm](https://user-images.githubusercontent.com/2529208/30991581-7412c10c-a45a-11e7-94f3-6e3d0fdd2acf.png)

### Steps to reproduce the behavior

Using v2.4.2 of rollup-plugin-vue, and latest versions of Vue and all other packages, I was having no trouble compiling and running.

Updating to v2.5.0 I get the above error (see screen shot) when trying to compile.

Rollup Config follows:

```
const buble = require('rollup-plugin-buble');
const commonjs = require('rollup-plugin-commonjs');
const copy = require('rollup-plugin-copy');
const livereload = require('rollup-plugin-livereload');
const resolve = require('rollup-plugin-node-resolve');
const replace = require('rollup-plugin-replace');
const serve = require('rollup-plugin-serve');
const uglify = require('rollup-plugin-uglify')
const vue = require('rollup-plugin-vue');

const config = {
  name: 'FleetApp',

  input: 'src/main.js',
  output: {
    file: './build/assets/js/bundle.js',
    format: 'umd'
  },

  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
    }),
    serve({
      open: true,
      contentBase: ['build'],
    }),
    livereload(),
    resolve(),
    commonjs(),
    vue({
      css: './build/assets/css/bundle.css'
    }),
    buble(),
    ( process.env.NODE_ENV === 'production' && uglify() ),
    copy({
      'src/index.html': './build/index.html',
      'src/static': './build/static'
    })
  ],

  globals: {
    vue: 'Vue'
  }
}

export default config;
```

**Comment by EvilClosetMonkey** [comment]
Just discovered that 'vue-template-compiler' was moved to a `devDependency` so I had to add it manually to my own package.json.

Shouldn't that be a peerDependency though?

**Comment by znck** [comment]
It should be a dependency and match with vue version too. I'll do a patch release soon.

**Comment by EvilClosetMonkey** [comment]
Thanks.

While looking into this issue I ran across a similar issue for 'vue-loader'. They had moved it to a peerDependency - the rationale being that you had more flexibility in the version you installed (if I remember correctly). I don't know enough about all the intricacies to have an opinion - just sharing what I found.

https://github.com/vuejs/vue-loader/issues/560

**Comment by znck** [comment]
Should be resolved in https://github.com/vuejs/rollup-plugin-vue/releases/tag/v2.5.1

**Comment by jonataswalker** [comment]
@znck It doesn't seem you published the new version.

**Comment by znck** [comment]
Published.

**Comment by jonataswalker** [comment]
Still `2.5.0`

**Comment by znck** [comment]
Sorry for inconvenience. I'll investigate.
