### ISSUE TITLE
Question: How to create inline sourcemap for stylus compilation

### ISSUE THREAD

**Issue by henryoliver** [vuejs/rollup-plugin-vue#141]
How to create inline sourcemap for stylus compilation

Hi, appreciate any example here of how inline source mapping could be generated through configuration settings below:

```javascript
plugins: [
        vue({
            css: './client/dist/components.css',
            stylus: {
                use: [(nib)()],
                compress: false,
                linenos: true
            }
        }),
```

**Comment by znck** [comment]
Sourcemaps are not supported yet. We are working on a build tool agnostic SFC compiler (https://github.com/vuejs/vue-component-compiler/pull/29). This would ensure feature parity between `vue-loader`, `rollup-plugin-vue` and other similar libraries. It would take a few weeks to finalize till then I'm pausing further development on `rollup-plugin-vue`.

**Comment by znck** [comment]
`@vue/component-compiler` add inline source map for injected styles.

For extracted styles, yet to figure out.

**Comment by znck** [comment]
Closing this as:
> @vue/component-compiler add inline source map for injected styles.

And extracted styles would have source-map and it's responsibility of css-extraction plugin to add inline source-map.
