### ISSUE TITLE
trim style to eliminate new lines as result of padContent

### ISSUE THREAD

**Issue by yakovyarmo** [vuejs/rollup-plugin-vue#144]
https://github.com/vuejs/rollup-plugin-vue/blob/ea1459af0322cf918391e8ceebbf33accb659439/src/vueTransform.js#L148

**Comment by znck** [comment]
`padContent` is used to simplify source map generation. You can use any css processor to minify in production build.

**Comment by znck** [comment]
Okay. I'll keep it open and revisit after vuejs/vue-component-complier#29 is merged.

**Comment by znck** [comment]
`@vue/component-compiler` uses clean css to minimize each style tag separately.
