### ISSUE TITLE
Add documentation for vue-template-compiler options

### ISSUE THREAD

**Issue by yakovyarmo** [vuejs/rollup-plugin-vue#147]
I used the compileOptions -> modules,
I basically copied it from vue-loader.
Do you maybe want to add it to the documentation?

**Comment by znck** [comment]
Now, the plugin accepts same options as `@vue/component-compiler`. Need to document though.

**Comment by znck** [comment]
See  https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#compilercompiletemplate-options
