### ISSUE TITLE
"TypeError: Path must be a string. Received true"

### ISSUE THREAD

**Issue by woubuc** [vuejs/rollup-plugin-vue#152]
I'm just getting started with Rollup. When trying to import a .vue file, the plugin throws the following error:

```
[!] (vue plugin) TypeError: Path must be a string. Received true
src\js\ui\App.vue
TypeError: Path must be a string. Received true
    at error (H:\project\node_modules\rollup\dist\rollup.js:185:14)
    at Promise.resolve.then.catch.err (H:\project\node_modules\rollup\dist\rollup.js:17584:6)
    at <anonymous>
```

This is my rollup.config.js file:
```Javascript
import vue from 'rollup-plugin-vue';
import commonjs from 'rollup-plugin-commonjs';
import minify from 'rollup-plugin-babel-minify';
import resolve from 'rollup-plugin-node-resolve';

export default {
	name: 'aw',
	input: 'src/js/index.js',
	output: {
		format: 'iife',
		file: 'build/bundle.js'
	},

	plugins: [
		resolve({browser: true, preferBuiltins: false}),
		commonjs(),
		vue(),
		minify({comments: false})
	]
};
```
I'm running Rollup with: `rollup --config --watch`. Going by the error message and the fact that I didn't provide any config, I think it's an issue with the module or with Rollup.

I checked that Rollup and all plugins are the latest published version on npm with `npm outdated`.

In case it could be an error in my code, here's my src/js/index.js (literally just these two lines, I commented out everything else and the error kept occuring):
```Javascript
'use strict';

import App from './ui/App.vue';
```

And src/js/ui/App.vue:
```HTML
<template>
	<h1>{{message}}</h1>
</template>

<script>
export default {
	data() { return {
		message: 'Hello world!'
	}}
}
</script>

<style scoped>
	h1 { color:red; }
</style>
```

**Comment by oskarrough** [comment]
Also seeing this. If you remove the `<style>` block the error goes away but I'm not sure how to debug further.

Is https://github.com/vuejs/rollup-plugin-vue/issues/132#event-1355893419 related?

**Comment by sorinsarca** [comment]
Bug comes from [postcss.js](https://github.com/vuejs/rollup-plugin-vue/blob/master/src/style/postcss.js#L17), which uses [postcss-load-config](https://github.com/michael-ciniawsky/postcss-load-config/blob/master/index.js#L48), the later one depends on some old version of [cosmiconfig](https://github.com/davidtheclark/cosmiconfig/blob/334065d9f7b557170a38b3f920bf5e90cecfab72/index.js#L22).

So, if you follow the code from links, you'll find out that passing only `--config` you'll get a boolean (true). 
You must use the config file name to avoid this bug: `rollup --config rollup.config.js --watch`

There is not need to set `autoStyles: false` nor remove the `<style>` blocks.

**Comment by znck** [comment]
With v4+, styles are handled in different fashion. This issue is invalid now. 

Related  #184
