### ISSUE TITLE
Example doesn't work using Rollup CLI

### ISSUE THREAD

**Issue by rbrtmrtn** [vuejs/rollup-plugin-vue#156]
### Expected behavior

When I follow the instructions in the example for building via Rollup CLI, I expect it to output a bundle to the `dist` directory.

### Actual behavior

It throws an error:

```[!] Error: Cannot find module '../dist/rollup-plugin-vue.common.js'```

So, the first thing that's missing is -- the instructions should say you have to `cd .. && npm install && npm run build` first before running the example.

Then, I got another error:

```
[!] Error: You must specify options.format, which can be one of 'amd', 'cjs', 'es', 'iife' or 'umd'
```

There's also a warning:

```
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
--output is now --output.file
```

So it seems the API has changed since this example was written. Just wanted to give a heads up :)

### Steps to reproduce the behavior

Follow the instructions in `example/README.md`.

**Comment by rosdi** [comment]
Hi has there been a regression? I am still getting `[!] Error: Cannot find module '../dist/rollup-plugin-vue.common.js'` when I follow the example README.md

Then I did `cd .. && npm install && npm run build` and then followed the README.md again, this time I got this error (I must be doing something very stupid):

```
C:\repos\rollup-plugin-vue\example [master ≡ +1 ~3 -0 !]> rollup -c --input Hello.vue
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
name is now output.name
format is now output.format

Hello.vue → stdout...
[!] TypeError: Cannot read property 'script' of undefined
TypeError: Cannot read property 'script' of undefined
    at resolveVuePart (C:\repos\rollup-plugin-vue\dist\rollup-plugin-vue.common.js:74:24)
    at resolveId (C:\repos\rollup-plugin-vue\dist\rollup-plugin-vue.common.js:103:23)
    at C:\Users\VirtualCalibre\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:5977:113
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```
