### ISSUE TITLE
Template parsing error: JavaScript expressions with `<` character

### ISSUE THREAD

**Issue by mglukhovsky** [vuejs/rollup-plugin-vue#159]
### Expected behavior

I have a single-file component with a Vue template that uses the following JavaScript ternary expression:
```js
{{amount < 2 ? 'less' : 'greater'}}
```
I expect it to render the template correctly.

### Actual behavior

This expression fails with `Parse Error: < 2 ? 'less' : 'greater'}}. Curiously, this works:
```js
{{amount > 2 ? 'greater' : 'less'}}
```

It looks like it's choking on the `<` character. (Possibly because a parser thinks it's an HTML element.)

### Steps to reproduce the behavior
Here's a JSFiddle showing that this works correctly with Vue on its own: https://jsfiddle.net/mglukhovsky/7o1mdmrp/1/

Here's a repo that reproduces this issue with `rollup-plugin-vue`: https://github.com/mglukhovsky/rollup-plugin-vue-bug

Here's a direct link to the single file component causing the error: https://github.com/mglukhovsky/rollup-plugin-vue-bug/blob/master/src/components/App.vue

Thanks for all your hard work on an excellent library! ⭐️

**Comment by znck** [comment]
Template is processed by a shared package (`@vue/component-compiler-utils`, used by `vue-loader` too). Should be fixed in v4+
