### ISSUE TITLE
Support for functional templates

### ISSUE THREAD

**Issue by Infeligo** [vuejs/rollup-plugin-vue#163]
While this is not directly stated in the documentation, judging from the problems I have and browsing through the source code and tests, `rollup-plugin-vue` does not properly support functional templates (unlike [vue-loader](https://vue-loader.vuejs.org/en/features/functional.html)). 

My components compile without any problems and warnings, but throw errors when used in runtime. These problems are related to render context. I do have `webpack` and `vue-loader` configured in parallel and the same components work with the latter combination without any problems.

Am I right in my guess about the functional templates? Can this support be implemented?

**Comment by znck** [comment]
Functional components are not yet supported. It would be supported in a couple of weeks.

**Comment by andreasvirkus** [comment]
Any updates on this?

**Comment by znck** [comment]
There is an experimental release (v4.0.0-alpha.1) which is using new vue-component-compiler. It would have multiple breaking changes in coming weeks.

**Comment by znck** [comment]
Shipped in v4.0.0
