### ISSUE TITLE
Parsing templates with a self-closing <iframe /> causes error

### ISSUE THREAD

**Issue by rbrtmrtn** [vuejs/rollup-plugin-vue#164]
### Expected behavior

When I run Rollup, I expect it to bundle my Vue components and other JS.

### Actual behavior

Everything gets bundled except for one `.vue` file which throws an error:

    Cannot read property 'startOffset' of undefined

### Steps to reproduce the behavior

I narrowed the issue down to [this line](https://github.com/vuejs/rollup-plugin-vue/blob/ea1459af0322cf918391e8ceebbf33accb659439/src/vueTransform.js#L184) in `rollup-plugin-vue`.

The problem seems to be that the `<template>` in this particular file contains an `<iframe>` . When I comment that out, it works fine.

The bigger problem would appear to be that  `parse5` doesn't parse the template correctly when it contains an `<iframe>`. Of course, that has nothing to do with `rollup-plugin-vue` but perhaps there could be some more checking to make sure the expected start/end tags are there before getting offsets?

**Comment by rbrtmrtn** [comment]
I've been testing this against `parse5` by itself and it seems like it's only _self-closing_ iframes that cause the error. I made an [issue](https://github.com/inikulin/parse5/issues/233) on their repo.

**Comment by rbrtmrtn** [comment]
Per [a comment](https://github.com/inikulin/parse5/issues/233#issuecomment-355763772) on the `parse5` [issue](https://github.com/inikulin/parse5/issues/233):

> The end result is that spec-compliant HTML parser must ignore the slash in `<iframe />`, so closing tags for `<div>` and `<template>` are still inside the `<iframe>` and don't really close anything.

So it seems like `<iframe />` just isn't valid. The easy solution for me is to just add the end tag, however -- this template works fine using `vue-loader`, so I feel like this might still highlight a parity issue.

@znck Is there any particular reason `rollup-plugin-vue` uses `parse5` instead of `vue-template-compiler`?

**Comment by znck** [comment]
It is a long pending task: remove parse5 dependency. I am working on vue-component-compiler that would handle this and all other vue specific compilation caveats. vue-component-compiler would replace parse5.

**Comment by rbrtmrtn** [comment]
Got it. Looking forward to `vue-component-compiler`, sounds like a nice solution. I'll go ahead and close this out.
