### ISSUE TITLE
Styles and template for a vue component not being compiled when used along with src attribute

### ISSUE THREAD

**Issue by urstrulyKarthik** [vuejs/rollup-plugin-vue#171]
### Expected behavior
Consider a vue component HelloWorld.vue withe the following content:
\<template src="./template.html"\>
\</template\>
<script src="./script.js">
</script>
<style src="./styles.css">
</style>
Rollup with options compileTemplate: true and css: true is not compiling the template and styles.
### Actual behavior
Roll up should be able to generate the template and styles section as a part of the module built.
### Steps to reproduce the behavior
Rollup the above component with rollup-plguin-vue plugin with template.html, script.js & styles.css available in the component (HelloWorld.vue) directory path

**Comment by Alfredo-Delgado** [comment]
If I try to use this syntax `<style lang="scss" src="./styles/component.scss"></style>` then I get an error of:` [!] (vue plugin) Error: Invalid CSS after "<": expected 1 selector or at-rule, was "<template>"`

**Comment by znck** [comment]
Please retry with latest release, it should be fixed.

Please reopen the issue, if the bug persists.
