### ISSUE TITLE
Update coffeescript

### ISSUE THREAD

**Issue by david-dlc-cerezo** [vuejs/rollup-plugin-vue#173]
Coffee-script references should be updated. `npm install` throws the forrowing warnings:
```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated coffeescript-compiler@0.1.1: No longer maintained.
```

https://github.com/vuejs/rollup-plugin-vue/blob/9e1b315857e99e84e6b5ff31cc9ee422d6abb7eb/package.json#L82
https://github.com/vuejs/rollup-plugin-vue/blob/9e1b315857e99e84e6b5ff31cc9ee422d6abb7eb/package.json#L83

**Comment by znck** [comment]
Script content is converted to import statements so coffeescript plugin can handle it. 

Related #153
