### ISSUE TITLE
(vue plugin) TypeError: Cannot read property 'startOffset' of undefined

### ISSUE THREAD

**Issue by francoisromain** [vuejs/rollup-plugin-vue#174]
Hello and thank you for the plugin. 
Following the rules of [vue-eslint](https://github.com/vuejs/eslint-plugin-vue), I removed the closing tag in `<textarea
          ref="field"
          v-model="fields"
          @keyup="resize" ></textarea>` to `<textarea
          ref="field"
          v-model="fields"
          @keyup="resize" />`. 

This makes an error: `[!] (vue plugin) TypeError: Cannot read property 'startOffset' of undefined`

**Comment by ZainW** [comment]
I have the exact error with my textarea tags as well.

temporarily removed the lint rule for that line

**Comment by znck** [comment]
Template parsing and processing is handled by `@vue/component-compiler-utils` which is shared with `vue-loader` too. This should be resolved now. 

Please reopen if not resolved.

**Comment by iKarev** [comment]
I have no textareas in project, but having exactly the same error. What can be the root of this problem? It's a new project with a few components. And no links to the source of problem in my code ((
