### ISSUE TITLE
Spread operator meets unexpected token error

### ISSUE THREAD

**Issue by FlandreDaisuki** [vuejs/rollup-plugin-vue#175]
### Expected behavior

Build successfully.

### Actual behavior

```
index.js → out.js...
[!] Error: Unexpected token
App.vue (14:4)
12: export default {
13:   computed:{
14:     ...mapState(['list'])
        ^
15:   }
16: }
```
### Steps to reproduce the behavior

https://github.com/FlandreDaisuki/simple-vue-rollup-example

**Comment by znck** [comment]
Script content is processed with babel. You should check you have appropriate babel plugins.
