### ISSUE TITLE
Cannot compile <template> part of single file component?

### ISSUE THREAD

**Issue by 1000ch** [vuejs/rollup-plugin-vue#177]
I am trying to switch to TypeScript from Babel, but getting unexpected behavior, it throws `[!] Error: Unexpected token`.

If I separate `<template>` part into HTML files and load it from `<template src=".html">`, build finishes without error.

### Steps to reproduce the behavior

1. Clone `typescript` branch of https://github.com/1000ch/vue-grd.
2. `npm install`
3. `npm run build`

**Comment by znck** [comment]
It works for test fixture: https://github.com/vuejs/rollup-plugin-vue/blob/534c04b7758deecc13d0b4d90bc04125bf022c75/test/fixtures/with-script-typescript.vue#L1-L16

Re-open if issue persists.
