### ISSUE TITLE
add option to use vue-template-compiler ssrCompile instead of compile

### ISSUE THREAD

**Issue by Askoth** [vuejs/rollup-plugin-vue#178]
### Expected behavior
This will allow compiled render functions that use the ssr methods to create the render string which are much faster to render html.

Without ssrCompile we also don't have the data attribute to trigger hydration in client vue.

### Actual behavior
There is no way to call ssrCompile thus the render functions are slower than actually letting vue parse the template strings in server side.

### Steps to reproduce the behavior
- only the compile behavior is possible, any use of the plugin will do it.

### Useful links:
https://www.npmjs.com/package/vue-template-compiler#compilercompiletemplate-options
https://ssr.vuejs.org/en/hydration.html
https://www.npmjs.com/package/vue-template-compiler#compilerssrcompiletemplate-options

### Proposed change
https://github.com/Askoth/rollup-plugin-vue/commit/d5a17f68fc459c61eb23946382525f4157ce8ac8

### Final considerations:
I didn't open a pull request in a feature branch of this repo because:
- I don't really have a production case for this however it's pretty handy while I'm investigating ssr in non node environments. Please let me know what you think.
- I don't know how to write tests for this. I believe the only way would be to check the compiled render function and check matches for _ssrNode or _ssrEscape?

**Comment by znck** [comment]
We would be using `vue-component-compiler` in next version. It would address this and all feature parity issues.
