### ISSUE TITLE
Throw if there are some postcss plugins not been installed

### ISSUE THREAD

**Issue by xing-zhi** [vuejs/rollup-plugin-vue#179]
### Expected behavior
If there are some postcss plugins not been installed, it should throw, like the postcss-cli.

### Actual behavior
If there are some postcss plugins not been installed, it outputs the css silently.

### Steps to reproduce the behavior
Uninstall some postcss plugins and run again.

**Comment by znck** [comment]
For inspiration, see https://github.com/vuejs/component-compiler-utils/issues/8
