### ISSUE TITLE
Why style.module attr is required when using vue({ css: false })?

### ISSUE THREAD

**Issue by laevilgenius** [vuejs/rollup-plugin-vue#186]
Styles without module attr are filtered out when `{ css: false }`, which breaks `scopeId` injection into template.
Relevant piece of code:
https://github.com/vuejs/rollup-plugin-vue/blob/4110dbb13594c3d0de8386d5eb74d9d773fe3231/src/index.js#L128-L147

**Comment by znck** [comment]
Oh! We have to take care of `scoped` styles too. 👏 Nice catch.
