### ISSUE TITLE
createVuePartRequest is not Windows-friendly

### ISSUE THREAD

**Issue by laevilgenius** [vuejs/rollup-plugin-vue#187]
`createVuePartRequest` keeps backslashes in created request, which causes all kinds of problems. Specifically: rollup strips those backslashes away, resulting in mangled _filename_.

**Comment by znck** [comment]
Could you please provide some concrete examples?

**Comment by laevilgenius** [comment]
```
rollup.rollup({
    input: './test.vue',
    plugins: [
        vue()
    ]
})
```
```
<template>
<div class="test">Foo</div>
</template>

<script>
export default {}
</script>
```
It throws `TypeError: Cannot read property 'script' of undefined`.
Transform function returns something like this:
```
/* script */

            export * from 'D:\absolute\path\test.vue?{"type":"script"}#.js'
            import script from 'D:\absolute\path\test.vue?{"type":"script"}#.js'
            const __vue_script__ = script
            
/* template */
...
```
If I modify `createVuePartRequest` to replace backslashes with forward slashes it almost works (I have to replace them back in `resolveId` for other internals to work properly).

**Comment by znck** [comment]
Thanks for example. I'm looking into it.

**Comment by bobmcallan** [comment]
Concur, same issue when upgraded to latest Rollup and compile vue.

`var _rollupConfig = [
    vue(
        {
            autoStyles: false,
            styleToImports: true,
            compileTemplate: true
            // css: _dist + _cssbundle
        }),`

`TypeError: Cannot read property 'script' of undefined
    at resolveVuePart (F:\Bob.Home\Development\Containerchain - Subsidium.v3\Subsidium.Client\node_modules\rollup-plugin-vue\dist\rollup-plugin-vue.common.js:74:24)
    at resolveId (F:\Bob.Home\Development\Containerchain - Subsidium.v3\Subsidium.Client\node_modules\rollup-plugin-vue\dist\rollup-plugin-vue.common.js:103:23)
    at F:\Bob.Home\Development\Containerchain - Subsidium.v3\Subsidium.Client\node_modules\rollup\dist\rollup.js:5977:113
    at <anonymous>`
