### ISSUE TITLE
Inject inline style as many times as v-for items when use v-for template

### ISSUE THREAD

**Issue by FlandreDaisuki** [vuejs/rollup-plugin-vue#197]
### Expected behavior

Like v3, generate 1 global style sheet and inject once.

### Actual behavior

As title when I use `<MyComponent v-for="item in itemList"></MyComponent>`

### Steps to reproduce the behavior

Clone [this repo](https://github.com/FlandreDaisuki/simple-vue-rollup-example/tree/v4-issue197) and checkout `v4-issue197` branch.
Then use `rollup -c` and open `index.html`

** I can't build with `rollup-plugin-vue@4.1.3`, so I use `rollup-plugin-vue@4.1.0`
** The error message of `rollup-plugin-vue@4.1.3` is pasted following:
<details>

<summary>[!] (vue.delegate plugin) TypeError: Cannot read property 'stringify' of undefined</summary>

```
$ rollup -c

src/index.js → ./index.js...
[!] (vue.delegate plugin) TypeError: Cannot read property 'stringify' of undefined
src/App.vue
TypeError: Cannot read property 'stringify' of undefined
    at error (/home/flandre/n/lib/node_modules/rollup/dist/rollup.js:224:15)
    at /home/flandre/n/lib/node_modules/rollup/dist/rollup.js:17213:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

</details>

**Comment by znck** [comment]
Resolved in https://github.com/vuejs/vue-component-compiler/blob/master/CHANGELOG.md#332-2018-05-13.

Released with v4.1.4.
