### ISSUE TITLE
Version 4.1.3 cannot run

### ISSUE THREAD

**Issue by easonyq** [vuejs/rollup-plugin-vue#198]
### Expected behavior
The latest version (4.1.3) can run normally

### Actual behavior
There are two problems:

1. I wrote this last Friday (version 4.1.0) and succeeded.
    
    ```javascript
    const vue = require('rollup-plugin-vue')
    ```

    When I updated this morning (version 4.1.3), it threw an exception: `vue is not a function`

    After looking up the dist codes, I found that we should modify it to
    
    ```javascript
    const vue = require('rollup-plugin-vue').default
    ```

2. After doing above, there is still a problem remained:

    ```
    [!] (vue.delegate plugin) TypeError: Cannot read property 'stringify' of undefined
    src\page\vue-components\AppShell.vue
    TypeError: Cannot read property 'stringify' of undefined
        at Object.exports.createVuePartRequest (D:\mip-project\mip\node_modules\_rollup-plugin-vue@4.1.3
    @rollup-plugin-vue\dist\utils.js:41:72)
        at ...
    ```

    `createVuePartRequest` from `dist/util.js`, contains 
    ```javascript
    return `${path.basename(filename)}.${lang}?${querystring_1.default.stringify(query)}`;
    ```
    where `querystring_1` equals to `require('querystring')`.

    **The key point is** that `querystring` package uses CommonJs, not ES6 module. Below is `node_modules/querystring/index.js`:

    ```javascript
    exports.decode = exports.parse = require('./decode');
    exports.encode = exports.stringify = require('./encode');
    ```

    I don't know whether this is a source code bug or a build problem.

### Steps to reproduce the behavior

Just use rollup-plugin-vue with empty config.

```javascript
const vue = require('rollup-plugin-vue').default;

module.exports = {
    ...
    plugins: [
        ...
        vue()
    ]
}
...

**Comment by jonataswalker** [comment]
@znck  Doesn't we have a test to catch this kind of error?

**Comment by Mourdraug** [comment]
It looks like build error. Transpiler seems to mistake querystring for ES6 module and add .default before function calls.

**Comment by funkybob** [comment]
I've just hit this same bug. 4.1.0 works fine, 4.1.1+ all fail this way.

**Comment by Mourdraug** [comment]
Unfortunately 4.1.0 seems broken on Windows (at least for me) due to #187. If someone needs a quick fix until this is resolved, open `node_modules/rollup-plugin-vue/utils.js` and replace all `querystring_1.default.` with `querystring_1.` and save.

**Comment by easonyq** [comment]
@Mourdraug Actually I also encounter bugs on Windows and found #187. So I was glad after finding updated version (4.1.3) this week. But...

**Comment by znck** [comment]
@jonataswalker It should be caught in tests. Runtime transpilation of ts-jest is different from tsc. Looking into it.
