### ISSUE TITLE
Rollup: (!) Broken sourcemap Plugins that transform code (such as 'VuePlugin') should generate accompanying sourcemaps

### ISSUE THREAD

**Issue by SumNeuron** [vuejs/rollup-plugin-vue#214]
This might be a repeat (sorry if that is the case), I saw several issues for sourcemap issues...
To be honest, not quite sure what that means and why it is an issue...

searched for broken sourcemap in issues results in no issues, 

but searching for sourcemap gives 

- https://github.com/vuejs/rollup-plugin-vue/pull/139
- https://github.com/vuejs/rollup-plugin-vue/issues/92
- https://github.com/vuejs/rollup-plugin-vue/pull/24

which suggest that it is fixed?

**Comment by znck** [comment]
Fixed in #215
