### ISSUE TITLE
Support lang="stylus" in <style> blocks

### ISSUE THREAD

**Issue by akittas** [vuejs/rollup-plugin-vue#218]
Many of us prefer lang="stylus" for css style blocks in SFCs, [component-compiler-utils](https://github.com/vuejs/component-compiler-utils) already supports that, so maybe it's easy to add?

thanks for this great plugin!

**Comment by mycarrysun** [comment]
See #79

**Comment by akittas** [comment]
@mycarrysun don't know how #79 is relevant, since `rollup-plugin-vue` stopped supporting `lang="stylus"`  since version 4.x. However now it CAN be supported using the latest version of component-compiles-utils.

**Comment by mycarrysun** [comment]
Sorry @akittas I didn't look ahead for breaking changes - I'm extracting css with postcss now and found that pr when troubleshooting a current issue with order of imports for stylesheets.

**Comment by akittas** [comment]
@mycarrysun sure np, I wish I could contribute more to this PR, unfortunately my basic background is in Python, not js.
