### ISSUE TITLE
Security and other concerns

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/rollup-plugin-vue#221]
Thank you @znck for your good work.

version 4.3.1

The normalize script has some security concerns, the code `component.__file = "/Users/[username]/path/to/component.vue"` is rendering out sensitive information.

Beside that I don't see a way to get rid of the `__vue_create_injector__` code.

**Comment by znck** [comment]
Is it okay if the file path is relative to cwd? 

PS @Akryum: will devtools' open in editor work if `__file` is relative to cwd?

**Comment by miljan-aleksic** [comment]
For public projects that would be ok, for private ones still a concern. Could it be an optional setting?

**Comment by znck** [comment]
`__vue_create_injector__` is used to inject styles to page at runtime. I have a WIP branch to remove it but it's blocked on https://github.com/vuejs/vue/issues/8296. non-SSR solution is ready though.

**Comment by miljan-aleksic** [comment]
Thanks @znck!

**Comment by miljan-aleksic** [comment]
@znck, sorry to bother again. I just realized the SSR scripts are still present when processing vue files.

**Comment by znck** [comment]
Maybe I missed something. I'll check again.

**Comment by miljan-aleksic** [comment]
@znck, did you got the chance to check this?

**Comment by miljan-aleksic** [comment]
@znck, seems I found the issue, reported at https://github.com/vuejs/vue-component-compiler/issues/77

**Comment by lukasjuhas** [comment]
Is there any workaround for this? My generated budnles have my path in them.. I've tried several things but I cannot get it to dissapear. (`component.__file`)
