### ISSUE TITLE
Coaxing the plugin to produce ES5

### ISSUE THREAD

**Issue by alexzorin** [vuejs/rollup-plugin-vue#223]
### Expected behavior
The bundle produced by Rollup/Vue plugin should be able to produce valid ES5 code.

### Actual behavior
Vue template functions (such as `__vue_create_injector__`) are using ES6 features like block-scoped variables/`let`:

```javascript
      if (!style.ids.includes(id)) {
        let code = css.source;
        let index = style.ids.length;

        style.ids.push(id);
```

### Steps to reproduce the behavior
Build the `cookbook/library` project. Each bundle produced uses `let`. 

I would greatly appreciate any guidance on how I can get the output to be transpiled to ES5, I was not able to figure it out on my own and am not sure whether it's a defect or not.

The reason I need this is that some projects using earlier versions of Webpack/UglifyJS can't deal with such bundles produced by Rollup. Shooting for compatibility here :) .

**Comment by alexzorin** [comment]
Interesting how it's always that you slave away for hours and fix the issue moments after asking for help ;).

Self-closing: Babel was set to exclude `*/**.vue`.

**Comment by YvanY** [comment]
I have the same promlem, how do you resolve this?
