### ISSUE TITLE
Provide option to post process styles

### ISSUE THREAD

**Issue by bnm12** [vuejs/rollup-plugin-vue#237]
Hi :)
We have a business case which requires us to do some post processing of the output of rollup-plugin-vue and since we lack a plugin system I've had to make this fork to achieve our goal: https://github.com/bnm12/rollup-plugin-vue
unfortunately now we have to maintain a parallel implementation of this where we would much rather maintain a plugin which is not impacted by every code change here.
It also just feels plain wrong to have this very specific feature code inside rollup-plugin-vue - it feels more like a plugin kind of thing

**Comment by znck** [comment]
I would prefer to use rollup's plugin system rather than re-inventing the wheel. 

Could you provide some use cases (or reasons) for your fork?
