### ISSUE TITLE
Error: Multiple conflicting contents for sourcemap source.

### ISSUE THREAD

**Issue by Lee-Heisenbug** [vuejs/rollup-plugin-vue#238]
Hi.
I was trying to use rollup to build a simple vue app. But an error occur every time I changed the style of a component.

![rollup-issue](https://user-images.githubusercontent.com/26576701/46779115-1a28fa80-cd49-11e8-98f3-ac79c83496a8.jpg)

I don't know how to fix it. Here is the project file: [rollup-issue.zip](https://github.com/vuejs/rollup-plugin-vue/files/2467294/rollup-issue.zip)

### Steps to reproduce the behavior
1. Down load the project file.
2. run "npm i".
3. run "npm run watch".
4. make some change to the style block of ./src/app.vue. And the error will show up.

**Comment by Lee-Heisenbug** [comment]
It seems could be fixed by using old version(4.2.0) of rollup-plugin-vue.

**Comment by touho** [comment]
Thank you so much for sharing the solution! Hope this will be fixed in future releases.

**Comment by BryceMehring** [comment]
Is there an update on this issue? Watching is currently not possible if source maps are enabled.

**Comment by kekeqy** [comment]
I have the same problem.This problem occurred when I used the <router-link> tag to open a routing address with parameters.

**Comment by lovelyMonkey** [comment]
I have the same problem when save the vue file

**Comment by r4fx** [comment]
same here with `rollup 1.7.4` and `rollup-plugin-vue 4.7.2` after editing vue SFC

**Comment by Lee-Heisenbug** [comment]
@r4fx My projects are currently using rollup 0.65.0 and rollup-plugin-vue 4.2.0. Not sure if this could be a work around. Here is the devDependencies of one of my projects:

"devDependencies": {
    "babel-core": "^6.26.3",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "dat.gui": "^0.7.3",
    "node-sass": "^4.9.3",
    "rollup": "^0.65.0",
    "rollup-plugin-babel": "^3.0.7",
    "rollup-plugin-clear": "^2.0.7",
    "rollup-plugin-commonjs": "^9.2.0",
    "rollup-plugin-copy-assets": "^1.0.0",
    "rollup-plugin-cpy": "^1.1.0",
    "rollup-plugin-ignore": "^1.0.5",
    "rollup-plugin-livereload": "^0.6.0",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-replace": "^2.0.0",
    "rollup-plugin-scss": "^0.4.0",
    "rollup-plugin-serve": "^0.4.2",
    "rollup-plugin-svgo": "^1.0.2",
    "rollup-plugin-uglify": "^5.0.2",
    "rollup-plugin-vue": "4.2.0",
    "vue-template-compiler": "^2.5.17"
  }

**Comment by jackprosser** [comment]
Any news on this? This has been open for a while now and it's a fairly major issue during development.

**Comment by arantes555** [comment]
Just ran into this as well. Seems to be some interaction with rollup-plugin-replace

**Comment by sandrina-p** [comment]
rolling back to  v4.2.0 solves the problem. However, we need the latest version that solves other previous bugs. Can you tell us (or do you know) when this issue will be a priority to fix?

**Comment by cawa-93** [comment]
Almost a year has passed since the problem was created. Milestone is version 4.7, but the latest version is 5.0.1. Everything looks like there will never be a solution :(

**Comment by taoeffect** [comment]
Hi, I will donate $200 in BTC to whoever gets a perfect fix to this problem merged into rollup/rollup-plugin-vue. Offer expires in 1 month (September 16th, 2019).

**Comment by darionco** [comment]
Not a "fix" but a plausible solution was committed in 3f879f3

It seems it has to do with how rollup's `watch` works and the source maps accumulating in the plugin. To bypass the issue, set `needMap` to `false` in your options:
```
config.plugins.push(vue({
    needMap: false,
}));
```

I am using TypeScript and haven't found issues with the source maps even after adding that flag, so there's that, YMMV though

**Comment by znck** [comment]
Similar to #248, tracking there.

**Comment by akauppi** [comment]
FYI: @darionco 's fix worked for me. `rollup-plugin-vue` 5.1.6

**Comment by hy-inger** [comment]
@darionco 's fix worked for me too. rollup-plugin-vue 5.1.6

**Comment by athrunsun** [comment]
@darionco Your solution works for me, but what does `needMap: false` do?

**Comment by darionco** [comment]
I dug through the code back when I posted this solution, I can't remember what it does anymore but it is safe to use and it does NOT disable source maps...  

Maybe @znck remembers what it does? (he implemented it)

**Comment by znck** [comment]
needMap generates source maps for script block.

**Comment by athrunsun** [comment]
@znck So by setting `needMap: false`, I lost all source map support for `<style>` and `<script>` blocks in `.vue` files?

**Comment by znck** [comment]
Yep.

**Comment by AlttiRi** [comment]
`needMap: false` will break source maps for components – the code in script block will be undebugable (you can't set a break point).

![2](https://user-images.githubusercontent.com/16310547/90301366-1f58b280-dea8-11ea-9428-d5bc4bb0112c.png)


But in additional it generates virtual js files, that contain only js code of component and it are debugable.

![1](https://user-images.githubusercontent.com/16310547/90301371-24b5fd00-dea8-11ea-89aa-2a5620454017.png)

Without `needMap: false` I get the correct source map for components:

![3](https://user-images.githubusercontent.com/16310547/90301475-c8071200-dea8-11ea-99ae-40b04799b074.png)

But in this case I can't use `watcher` for auto rebuilding, it will throw `UnhandledPromiseRejectionWarning: Error: Multiple conflicting contents for sourcemap source`.


```js
const watchOptions = {
    ...inputOptions,
    output: [outputOptions],
    watch: {
        skipWrite: true,
    }
};

const watcher = watch(watchOptions);
watcher.on("event", async event => {
    if (event.code === "BUNDLE_END") {
        const res = await event.result.generate(outputOptions); // Error
    }
});
```

**Comment by AlttiRi** [comment]
And it forces me to use full the Rollup rebuilding:
```js
watcher.on("event", async event => {
    if (event.code === "START") {
        await build();
    }
});
```

What takes noticeable additional time.

**Comment by AlttiRi** [comment]
I think this issue should be reopen. https://github.com/vuejs/rollup-plugin-vue/issues/248 is about related bug to this one, but it is not the same bug.

Currently it's impossible to use `watcher` if you use source map in output options of Rollup:
```js
const outputOptions = {
    sourcemap: true
};
```

Because you will get `UnhandledPromiseRejectionWarning: Error: Multiple conflicting contents for sourcemap source` on rebuilding after you have modified `style` or `template` block of a component.

**Comment by AlttiRi** [comment]
[This poll request](https://github.com/vuejs/rollup-plugin-vue/pull/375) (not accepted) fixes this issue. But it applies only on 6.0.0. version of this plugin that works only with Vue 3.0.

Also I can note that `"rollup-plugin-vue": "^6.0.0-beta.10"` generates source map for virtual files **even** with `needMap: true` (with only debuggable `template` _(only for row html, not pug)_):
![qwe](https://user-images.githubusercontent.com/16310547/90303346-f63f1e80-deb5-11ea-84d8-76a23d4decc6.png)

Is it a bug? How to disable it?

**Comment by danielvy** [comment]
This bug should be reopened. It is still an issue with v6.0.0 and it is not the same bug as #248.

It prevents using watch mode when source maps are needed.
