### ISSUE TITLE
Cannot find module 'vue-template-compiler'

### ISSUE THREAD

**Issue by hosein2398** [vuejs/rollup-plugin-vue#245]
### Expected behavior
Create sound output

### Actual behavior
Throwing error

I was trying out minimal example that i faced this :
```
[!] Error: Cannot find module 'vue-template-compiler'
Error: Cannot find module 'vue-template-compiler'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hosein/Documents/testing pa...
```
Installing `vue-template-compiler` manually solved it.

Depenedecies:
```
"rollup": "^0.67.3",
"rollup-plugin-vue": "^4.3.2",
```
rollup config:
```
import vue from 'rollup-plugin-vue'

export default {
  input: './comp.vue',
  output: {
    format: 'esm',
    file: 'dist/MyComponent.js'
  },
  plugins: [
    vue()
  ]
}
```

**Comment by hosein2398** [comment]
I guess everyone knows that it would work that way, this was opened cause i wonder why it's not installed by default.

**Comment by Justineo** [comment]
`vue-template-compiler` is listed in `peerDependencies` so it is expected. You should had seen a warning when you install `rollup-plugin-vue` without `vue-template-compiler`.

**Comment by nmxiaowei** [comment]
it is bug @hosein2398
