### ISSUE TITLE
Empty helper file?

### ISSUE THREAD

**Issue by StevenLiekens** [vuejs/rollup-plugin-vue#255]
What is the purpose of this empty file?

https://github.com/vuejs/rollup-plugin-vue/blob/27bc6f8d5981dc47ec3daa253682c684434e7d51/test/assertions.ts

It's used here but I have no clue what this does.

https://github.com/vuejs/rollup-plugin-vue/blob/27bc6f8d5981dc47ec3daa253682c684434e7d51/test/baseline.spec.ts#L4

https://github.com/vuejs/rollup-plugin-vue/blob/27bc6f8d5981dc47ec3daa253682c684434e7d51/test/baseline.spec.ts#L27-L28

**Comment by znck** [comment]
It can be used to add additional assertions for a particular test fixture.

**Comment by StevenLiekens** [comment]
How does that work if the file is empty?

**Comment by znck** [comment]
Oh! There is no specific test yet.

**Comment by StevenLiekens** [comment]
I'm still confused about the import from a file with no exports (or anything at all).🤔

**Comment by znck** [comment]
I'll add an example for demonstration.
