### ISSUE TITLE
Server side support

### ISSUE THREAD

**Issue by glopezep** [vuejs/rollup-plugin-vue#263]
### Version
greater than 4.3.2

### Steps to reproduce
create a build with rollup

### What is expected?
it should not use document, window or navigator

### What is actually happening?
the build should be universal,.

**Comment by znck** [comment]
There is an option to generate an SSR bundle. (https://rollup-plugin-vue.vuejs.org/options.html#template-optimizessr)

There is an example as well: https://rollup-plugin-vue.vuejs.org/examples.html#ssr

All the code generated, other than style injection code (which is different for server and browser), is universal. Even for style-injection, you can override: https://rollup-plugin-vue.vuejs.org/options.html#styleinjector (default: https://github.com/znck/vue-runtime-helpers/tree/master/src/inject-style)

**Comment by lancetharper** [comment]
Would updating to the latest `vue-runtime-helpers` fix this? https://github.com/znck/vue-runtime-helpers/commit/02d9dfaf54388128a7eac8013f0af6526f6e8586
