### ISSUE TITLE
README lacks of information

### ISSUE THREAD

**Issue by y-nk** [vuejs/rollup-plugin-vue#269]
### Version
4.3.0

### Reproduction link
[https://github.com/vuejs/rollup-plugin-vue/blob/master/README.md](https://github.com/vuejs/rollup-plugin-vue/blob/master/README.md)

### Steps to reproduce
README provides minimal implementation mentioning `VuePluginOptions` but never links to actual set of options.

### What is expected?
have information about what kind of options we can put in.

### What is actually happening?
there's no such information.

**Comment by y-nk** [comment]
@znck can i know about the status of this ? why is it bindly closed without a message, PR or ?

**Comment by znck** [comment]
It was fixed by a commit (https://github.com/vuejs/rollup-plugin-vue/commit/515c3fe4e4d7aa990be5e607da36831881592b8b).
