### ISSUE TITLE
Library with cjs format got vue-runtime-helper

### ISSUE THREAD

**Issue by mazipan** [vuejs/rollup-plugin-vue#270]
### Version
4.7.2

### Description
I used [bili.js](https://bili.egoist.sh/#/) from @egoist that extend rollup-plugin-vue, when building library got this extra line

```
var __vue_normalize__ = _interopDefault(require('vue-runtime-helpers/dist/normalize-component.js'));
```

This line made my user got this error:

```
Module not found: Error: Can't resolve 'vue-runtime-helpers/dist/normalize-component.js'
```

### What is expected?
`vue-runtime-helpers` was included as part of script, not using external require.

### What is actually happening?
Using external require.

Related with: [https://github.com/mazipan/vue-google-adsense/issues/12](https://github.com/mazipan/vue-google-adsense/issues/12)

**Comment by zcuric** [comment]
👍

**Comment by ArjunAtlast** [comment]
+1

**Comment by xaksis** [comment]
@mazipan how did you resolve this?
