### ISSUE TITLE
Unknown transform 'collections'

### ISSUE THREAD

**Issue by chunzii** [vuejs/rollup-plugin-vue#273]
Hello, I am very confused about this issue. I am using Node 8.12.0, NPM 6.4.1. After npm install, I run rollup -c, I got below error. Thanks very much in advance!!!

c:\code\Support>rollup -c

```
./src/main.js → ./dist/assets/js/app.js...
[!] (vue plugin) Error: Unknown transform 'collections'
src\App.vue
Error: Unknown transform 'collections'
    at error (C:\Users\chuzho\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:168:15)
    at C:\Users\chuzho\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:17957:17
    at <anonymous>
```

Below is my package.json:

`{
  "scripts": {
    "build": "run-s build:**",
    "build:js": "cross-env NODE_ENV=production rollup -c",
    "build:autoprefixer": "postcss --use autoprefixer -o dist/assets/css/app.css dist/assets/css/app.css",
    "build:cssnano": "cssnano dist/assets/css/app.css dist/assets/css/app.css",
    "dev": "cross-env NODE_ENV=development rollup -cw"
  },
  "dependencies": {
    "axios": "0.18.0",
    "babel-polyfill": "6.26.0",
    "blueimp-canvas-to-blob": "3.14.0",
    "bowser": "1.9.3",
    "datauri": "1.1.0",
    "json2csv": "4.2.1",
    "lodash": "4.17.10",
    "querystring": "0.2.0",
    "rupture": "^0.7.1",
    "string-template": "1.0.0",
    "v-tooltip": "2.0.0-rc.32",
    "vue": "2.5.16",
    "vue-form": "4.9.0",
    "vue-router": "3.0.1",
    "vue-select": "2.4.0",
    "vue2-timepicker": "0.1.4",
    "vue2-touch-events": "1.0.0",
    "vuex": "3.0.1"
  },
  "devDependencies": {
    "@types/node": "7.0.60",
    "@babel/core": "7.0.0-beta.47",
    "@babel/plugin-transform-regenerator": "7.0.0-beta.46",
    "@babel/preset-env": "7.0.0-beta.47",
    "autoprefixer": "8.2.0",
    "babel-core": "6.26.0",
    "babel-plugin-external-helpers": "6.22.0",
    "babel-plugin-transform-object-rest-spread": "6.26.0",
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-preset-env": "1.7.0",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-es2017": "6.24.1",
    "cross-env": "5.1.4",
    "cssnano-cli": "1.0.5",
    "eslint-plugin-vue": "4.5.0",
    "npm-run-all": "4.1.2",
    "postcss-cli": "5.0.0",
    "rollup": "0.56.5",
    "rollup-plugin-alias": "1.4.0",
    "rollup-plugin-async": "^1.2.0",
    "rollup-plugin-babel": "3.0.4",
    "rollup-plugin-buble": "0.19.2",
    "rollup-plugin-commonjs": "8.2.1",
    "rollup-plugin-copy": "0.2.3",
    "rollup-plugin-eslint": "4.0.0",
    "rollup-plugin-image": "1.0.2",
    "rollup-plugin-json": "^3.1.0",
    "rollup-plugin-livereload": "0.6.0",
    "rollup-plugin-node-builtins": "2.1.2",
    "rollup-plugin-node-globals": "1.2.0",
    "rollup-plugin-node-resolve": "3.3.0",
    "rollup-plugin-nodent": "^0.2.2",
    "rollup-plugin-replace": "2.0.0",
    "rollup-plugin-serve": "0.4.2",
    "rollup-plugin-uglify": "3.0.0",
    "rollup-plugin-vue": "3.0.0",
    "stylus": "0.54.5",
    "vue-template-compiler": "2.5.16"
  }
}
`

My babelrc file:

`{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers",
    "transform-runtime",
    "transform-object-rest-spread",
    "@babel/plugin-transform-regenerator"
  ]
}
`

**Comment by boussou** [comment]
same here : not working

**Comment by tardyp** [comment]
This is because of rollup-plugin-vue 3.0.0 which is incompatible with whatever newer version of the stack (didn't check)

Upgrading to 5.x did fix the issue
