### ISSUE TITLE
Add support for dart-sass

### ISSUE THREAD

**Issue by nwpappas** [vuejs/rollup-plugin-vue#274]
### What problem does this feature solve?
Dart Sass is the primary implementation of Sass, which means it gets new features before any other implementation. It would allow for the greatest number of Sass functionality to be used in conjunction with Vue and Rollup.

The Sass project has an open issue on helping projects migrate:
https://github.com/sass/dart-sass/issues/267

### What does the proposed API look like?
The API should not change from a user point of view. The means of compiling Sass behind the scenes simply changes.

**Comment by znck** [comment]
It's an upstream change. https://github.com/vuejs/component-compiler-utils/pull/56

> keeping this issue open to track.

**Comment by gwardwell** [comment]
@znck It looks https://github.com/vuejs/component-compiler-utils/pull/56 has been merged, so I don't think this issue is blocked anymore. Is there any work to be done for this package to support dart sass or that I need to do to implement it?

**Comment by gwardwell** [comment]
@znck It looks like this issue can be closed now, right? I can across it when trying to determine if rollup-plugin-vue supports dart-sass and the Sass module system. After a little confusion, I just tried a sass module in my project and it worked. So this isn't waiting or blocked anymore, right?

**Comment by znck** [comment]
Yes, dart-sass is already supported.

**Comment by funyapu** [comment]
Hi,

It seems`@use` statement not working in both SFC and auto import.
Is this matter of upstream?

Replacing `@use` with `@import` solves build failure, but do print css multiple times :(
