### ISSUE TITLE
How to resolve @ prefixed paths (from the Vue webpack config)

### ISSUE THREAD

**Issue by sp00x** [vuejs/rollup-plugin-vue#275]
With the default Vue webpack config there is an alias set up so that @ resolves to src/, so e.g.  `import Foo from '@/components/Foo'` resolves to that path. 

Without resolving these paths, the dist/ output of rollup is just an unresolved reference to a `require` for the unresolved path, obviously something that will fail when distributing.

I guess this is more of a rollup question than rollup-plugin-vue maybe, but since it's related to using this plugin with a common Vue syntax, is there another plugin or something that can help resolve these paths properly? (I tried a few, but couldn't get any of them to work the same way the webpack one does)

**Comment by znck** [comment]
See https://github.com/rollup/rollup-plugin-alias
