### ISSUE TITLE
can not compile jsx in vue file

### ISSUE THREAD

**Issue by masongzhi** [vuejs/rollup-plugin-vue#278]
### Version
4.7.2

### Reproduction link
[https://github.com/masongzhi/vugular-ui](https://github.com/masongzhi/vugular-ui)

### Steps to reproduce
yarn build

### What is expected?
compile success

### What is actually happening?

![](https://user-gold-cdn.xitu.io/2019/3/21/1699e487b1f8a992?w=2428&h=478&f=png&s=114280)

**Comment by znck** [comment]
RPV does not process script code, it provides script code to other plugins like rollup-plugin-babel or rollup-plugin-typescript2.  Include required babel configuration for JSX, see https://github.com/vuejs/jsx

**Comment by masongzhi** [comment]
could you give a example code?

> RPV does not process script code, it provides script code to other plugins like rollup-plugin-babel or rollup-plugin-typescript2. Include required babel configuration for JSX, see https://github.com/vuejs/jsx

**Comment by masongzhi** [comment]
it is also error when i write from [https://github.com/vuejs/jsx](https://github.com/vuejs/jsx)
```
// rollup.config.js
import commonjs from 'rollup-plugin-commonjs';
import vue from 'rollup-plugin-vue';
import resolve from 'rollup-plugin-node-resolve';
import babel from 'rollup-plugin-babel';

export default {
  input: 'src/index.js',
  output: {
    format: 'esm',
    file: 'dist/index.js',
  },
  extensions: ['.js', '.vue'],
  plugins: [
    vue(),
    resolve({
      extensions: ['.js', '.vue'],
    }),
    commonjs(),
    babel({
      exclude: 'node_modules/**',
      runtimeHelpers: true,
    }),
  ],
};
```

```
// .babelrc
{
  "presets": ["@vue/babel-preset-jsx"]
}

```

**Comment by houd1ni** [comment]
@masongzhi  any success?

**Comment by zouhangwithsweet** [comment]
i found the same errror

**Comment by zouhangwithsweet** [comment]
when i use lang=babel in .vue file, it can work
```vue
<script lang="babel">
 // some code
</script>
```

**Comment by fubangfu** [comment]
const acornJSX = require( 'acorn-jsx' );

rollup({
...
acornInjectPlugins : [acornJSX( {       allowNamespaces : false   } )],
})

**Comment by Akryum** [comment]
@znck Still seing this error in 5.1.9. Building JSX in normal js files works, but not in .vue files.

**Comment by Akryum** [comment]
See #429
