### ISSUE TITLE
transformAssetUrls does not appear to work

### ISSUE THREAD

**Issue by leighPri** [vuejs/rollup-plugin-vue#279]
### Version
4.7.2

### Reproduction link
[https://github.com/leighPri/vue-rollup-error](https://github.com/leighPri/vue-rollup-error)

### Steps to reproduce
1. npm i
2. npm run build
3. npm run serve (easiest illustration of issue, not strictly necessary)

### What is expected?
Once served, a ? image (not text) should appear since the asset should be properly transformed.

### What is actually happening?
No image appears since the asset is ignored despite `transformAssetUrls` being set to `true`.

---
This is a simplified version of a multi-output component library we've been working on. The asset directory being copied to `dist` does not help this issue.

**Comment by LinusBorg** [comment]
[Your usage of the option](https://github.com/leighPri/vue-rollup-error/blob/master/rollup.config.js#L49) is incorrect. This option doesn't accept a boolean value.

As shown in the docs, it accepts an object that defines which elements and their respective attributes are transformed:

https://rollup-plugin-vue.vuejs.org/options.html#template-compileroptions

**Comment by leighPri** [comment]
That was a mistake when I put the example together from looking at vue-loader but I have tried explicitly setting that exact default object only to end up at the same issue.

**Comment by leighPri** [comment]
Not vue-loader. component-compiler-utils. Still, the issue persists.

**Comment by LinusBorg** [comment]
Can you update the example? 

We'll check it out.

**Comment by leighPri** [comment]
Done. Thank you!
