### ISSUE TITLE
Vue typescript component not working properly (mixin beforeCreate not called)

### ISSUE THREAD

**Issue by bebsworthy** [vuejs/rollup-plugin-vue#281]
### Version
5.0.0

### Reproduction link
[https://github.com/bebsworthy/rollup-demo-issue](https://github.com/bebsworthy/rollup-demo-issue)

### Steps to reproduce
# Basic steps

- Build the `library` with yarn (`yarn build` or `rollup -c`)
- Link the library in the application (`yarn link`)
- Serve the application (`yarn serve`)
- Open the browser and click on the read link "problem" this should display the component in a router-view
- The component should have $router and $route defined by vue-router but it doesn't because the mixin (including the vue-routeur mixin) are not triggered for that component. (confirmed by adding console.log in vue-router mixin)

# Detailed Steps

## library

The library projects. It generates an esm file using rollup.
It currently only has a single component `Simple` which only purpose is to demonstrate the issue.

```
yarn
yarn build
yarn link
```

## application

A default vue cli application project with babel, typescript, router.

You can launch the app and click on the link `problem` at the top.

```
yarn
yarn link "my-library"
yarn serve
```

The modified files are :

- src/router.ts (to add a route to the `Simple` component)
- src/App.vue (to add a `router-link`)
- src/maint.ts (to add a mixin `beforeCreate`)

### What is expected?
The component should load and the Vue mixin should be executed. 

### What is actually happening?
Something seems wrong with how the component is loaded.

- $router ($route, etc...) is not available on the `Simple` component.
- The mixins are not executed on the Simple component. (which explains the above, since the vue-router mixin 'beforeCreate' is not executed for that component)
- The Simple component has `_uid: 0` which is weird because App also has `_uid: 0` 
- The Simple component is invisible to Vue dev tool (Not sure if relevant)
- Probably other things...

---
Apologies in advance, I'm not sure it's an issue with this project, but I'm not sure where else to look.

**Comment by bebsworthy** [comment]
Caused by webpack double loading vue from the library node_modules and from the application node_modules.

**Comment by mjmnagy** [comment]
> 
> 
> Caused by webpack double loading vue from the library node_modules and from the application node_modules.

How would you determine if this is happening?
