### ISSUE TITLE
Target Web Components 

### ISSUE THREAD

**Issue by brion-fuller** [vuejs/rollup-plugin-vue#282]
### What problem does this feature solve?
This is current available in the Vue Cli to target web components but this uses webpack which doesn't support esm format.  
This scopes the styling to a shadowDom instead of the global dom.  I would imagine this would just return the default class of the main file.

### What does the proposed API look like?
`vue({target: 'wc', name:'my-web-component'})`

**Comment by znck** [comment]
I have written an article on this: https://znck.dev/blog/2019-shipping-web-components-with-vue.

However, the documentation should have examples for this.

**Comment by shaydoc** [comment]
Hey @znck 
Regarding shadow mode, I would like to build my components with shadowMode set to true, so when I wrap the modules inside web components within my consuming application, they we inject their styles into the shadow dom, could this switch be easily exposed by the vue options?
Could it also be done in such a way that only target components get compiled with shadowmode set to true also.
I have used the normaiser override but was hoping maybe the api of his plugin could support a shadow Mode flag and maybe a glob pattern to include/exclude from shadowMode injection
