### ISSUE TITLE
Allow option of choosing sass/scss implementation

### ISSUE THREAD

**Issue by TomCaserta** [vuejs/rollup-plugin-vue#288]
### What problem does this feature solve?
Since a couple versions back this plugin updated to use `sass` instead of `node-sass`. It would be good if the plugin could receive an `implementation` option for the scss compiler in order for the plugin user to specify what they would like to use. 

For my use case I have many plugins (functions) to node-sass that are simply not yet possible with the `sass` implementation, this means I cannot upgrade to the latest version of this plugin. 

This is similar to the option that is available in the sass-loader for webpack: https://github.com/webpack-contrib/sass-loader

### What does the proposed API look like?
```
{
    // ...
    style: {
        preprocessOptions: {
            scss: {
                implementation: require('node-sass'),
            },
        },
    },
}
```

**Comment by znck** [comment]
Closing it as it is included in #300.
