### ISSUE TITLE
the Problem of Repeated Import of Sass Files

### ISSUE THREAD

**Issue by muyi0327** [vuejs/rollup-plugin-vue#296]
How to Solve the Problem of Repeated Import of Sass Files?

c.scss

.test-color{color:blue}

in file a:
<style lang="scss">@import 'c.scss'</style>

in file b:
<style lang="scss">@import 'c.scss'</style>

config file:
vue({
            css: false,
            defaultLang: {
                style: 'scss'
            },
            style: {
                preprocessOptions: {
                    scss: {
                        data: parseJsonToSass({
                            prefix,
                            prefixCls
                        })
                    }
                },
                postcssPlugins: [
                    autoprefixer()
                ]
            }
        })

but in target file d.css

.test-color{color:blue}
.test-color{color:blue}

**Comment by rdunk** [comment]
The solution would be not to prepend SCSS files with classes in them to every file, instead only prepend files that contain your variables/functions/mixins.
