### ISSUE TITLE
how to handle duplicate imports in different files

### ISSUE THREAD

**Issue by muyi0327** [vuejs/rollup-plugin-vue#298]
### What problem does this feature solve?
how to handle duplicate imports in different files

### What does the proposed API look like?
```
style: {
                preprocessOptions: {
                    scss:(sassNodes)=>{
                        //donsomething
                   }
                }
```

**Comment by muyi0327** [comment]
I look at the source code.bug i have a question.you compile the style one by one.how to handle duplicate imports in different files？

such as:

in a.vue:
style
@import c.scss;

in b.vue
style
@import c.scss;

the code 
`const styles = await Promise.all(descriptor.styles.map(async (style) => {
                    if (style.content) {
                        style.content = prependStyle(filename, style.lang || 'css', style.content, style.map).code;
                    }
                  ........
                    return compiled;
                }));`

**Comment by znck** [comment]
Maybe use https://github.com/FullHuman/rollup-plugin-purgecss with `vue({ css: false })`.
