### ISSUE TITLE
Getting Uncaught TypeError: Failed to resolve module specifier "vue-runtime-helpers" when upgrade to 5.1.2 (Using ESM)

### ISSUE THREAD

**Issue by jrgleason** [vuejs/rollup-plugin-vue#308]
### Version
5.1.2

### Reproduction link
[https://github.com/jrgleason/personal-site-private](https://github.com/jrgleason/personal-site-private)

### Steps to reproduce
Use version 5.1.2

### What is expected?
No `import { normalizeComponent, createInjector } from 'vue-runtime-helpers';`

### What is actually happening?
`import { normalizeComponent, createInjector } from 'vue-runtime-helpers';` Added to file

---
I have been using this plugin for a long time (Thank you), however, when I upgrade to 5.1.2 I get the following error when I try to run...

     Uncaught TypeError: Failed to resolve module specifier "vue-runtime-helpers"

I checked and the difference is after upgrading this line is added to the rollup output...

    import { normalizeComponent, createInjector } from 'vue-runtime-helpers';

This is the line breaking my code and is not needed. I looked and this was the only change in 5.1.2.

In the meantime to fix the issue I have downgraded to the previous version (5.1.1).

**Comment by jrgleason** [comment]
At least can I get an option to disable it?

**Comment by redxtech** [comment]
I would like to second this. I would not like to be forced to bundle this with my plugins.

**Comment by znck** [comment]
The `vue-runtime-helpers` module was always inlined prior to `5.1.x`, this was a problem when packaging multiple components (e.g. in component libraries). However, no you can externalize it by setting the `external` option in rollup config.

And `vue-runtime-helpers` can be replaced with a custom implementation by providing https://rollup-plugin-vue.vuejs.org/options.html#normalizer.

**Comment by znck** [comment]
@redxtech Use https://github.com/rollup/rollup-plugin-node-resolve so that rollup can find the module in inline in the final bundle.
