### ISSUE TITLE
css style use new Set(),it will causes errors on older browsers,How to avoid using Set?

### ISSUE THREAD

**Issue by Sjk824** [vuejs/rollup-plugin-vue#316]
How to avoid using Set?
```
const group = isOldIE ? css.media || 'default' : id;
const style = styles[group] || (styles[group] = { ids: new Set(), styles: [] });
```

**Comment by znck** [comment]
You can use a polyfill from [polyfill.io](https://polyfill.io) - https://polyfill.io/v3/polyfill.min.js?features=Set

**Comment by grtan** [comment]
@znck Hope you to solve it as soon as possible, I have encountered this problem, and I raised this question a long time ago.

[https://github.com/znck/vue-runtime-helpers/issues/4#issue-496599975](https://github.com/znck/vue-runtime-helpers/issues/4#issue-496599975)
