### ISSUE TITLE
5.1.5 not on npm

### ISSUE THREAD

**Issue by simllll** [vuejs/rollup-plugin-vue#318]
### Version
5.0.0

### Reproduction link
[https://www.npmjs.com/package/rollup-plugin-vue](https://www.npmjs.com/package/rollup-plugin-vue)

### Steps to reproduce
in git there is already version 5.1.5 relased, but it's not found on npm. 

### What is expected?
5.1.5 on npm

### What is actually happening?
5.1.4 is on npm

**Comment by znck** [comment]
I think the release script failed. **Published now.**
