### ISSUE TITLE
Q: is this plugin needed for web apps, or just for sharing components?

### ISSUE THREAD

**Issue by akauppi** [vuejs/rollup-plugin-vue#325]
The [front page](https://github.com/vuejs/rollup-plugin-vue) of the project talks about components:

>Its difficult to share .vue components. Now roll your Vue components.

What if I'm only making a web app that *internally* uses `.vue` files but don't intend to export or share them? Do I still need this plugin?

**Comment by znck** [comment]
You can compile .vue files to ESM modules, if that’s what you need, you use Rollup.

Rollup is also capable of bundling applications but my personal opinion, webpack does that better.
