### ISSUE TITLE
Latest plugin version breaks IE11 adding arrow function in to bundled code

### ISSUE THREAD

**Issue by ale-grosselle** [vuejs/rollup-plugin-vue#341]
### Version
5.1.6

### Reproduction link
[https://github.com/ale-grosselle/vue-webcomponent](https://github.com/ale-grosselle/vue-webcomponent)

### Steps to reproduce
- Create an index.js 
- Create a simple SFC with a simple "style" section 
- Include SFC in index.js
- Bundle using rollup and rollup-plugin-vue

### What is expected?
In previous version, the piece of code included in my bundled code by vue plugin was ES5; now is ES6

### What is actually happening?
In bundled code, arrow function shouldn't be there, otherwise my code will not work in IE1

---

This plugin it uses "inject-style/browser.mjs", which include in my bundle this function:
```
function createInjector(context) {
    return (id, style) => addStyle(id, style);
} 
```
Including in my bundled code an arrow function, my library will not work in IE11

My actual workaround is to set my babel to transpile browser.mjs:
 ```
babel({ include: ["src/**", "node_modules/vue-runtime-helpers/dist/inject-style/browser.mjs"], plugins: [] }), // see .babelrc

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by aulonm** [comment]
I'm having the same problems, but for me the problems arise updating to any version above 5.0.1.. Haven't managed to come up with any workaround.

**Comment by znck** [comment]
The plugin uses some runtime helper functions to normalize .vue components. These helpers are written in ES2015, you have to transpile it with babel to support old browsers.

> P.S.: If you need help with rollup config to do so, you can reach out to me on discord.

**Comment by nils-christian** [comment]
Hello,

Can you please provide the required config in this ticket as workaround? I assume that some more people will encounter this issue.

Thank you and best regards

  Nils

**Comment by nlien** [comment]
This is my configuration... Hope it helps...

*rollup.config.js*
```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          browsers: [
            "> 1%",
            "last 2 versions",
            "IE 11"
          ]
        }
      }
    ]
  ],
  plugins: [
    '@babel/plugin-transform-arrow-functions',
    '@babel/plugin-proposal-optional-chaining'
  ]
}
```

*babel.config.js*

```
import resolve from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'
import babel from '@rollup/plugin-babel'
import VuePlugin from 'rollup-plugin-vue'
import pkg from './package.json'

const version = process.env.VERSION || require('./package.json').version
const banner =
  `/*!
  * myModule v${version}
  */`
const name = 'smartforms'

export default {
  input: 'index.js',
  output: [
    { file: pkg.main, format: 'cjs', banner, name },
    { file: pkg.module, format: 'es', banner, name },
    { file: pkg.browser, format: 'umd', banner, name }
  ],
  plugins: [
    VuePlugin(),
    resolve({
      extensions: ['.js', '.vue']
    }), // so Rollup can find external dependencies
    commonjs(), // so Rollup can convert CJS modules to ES6
    babel({
      babelHelpers: 'bundled'
    })
  ]
}
```
