### ISSUE TITLE
v6-beta breaks sass style

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/rollup-plugin-vue#345]
I could not use the issue creator because it didn't have v6-beta.

On v6-beta: As soon as I use 
```
<style lang="sass" scoped>
div
  color: blue
</style>
```
in my code, it will not compile and gives `Unknown word` error.

**Comment by PickRelated** [comment]
This needs to be addressed I suppose. Can we reopen this?

**Comment by mesqueeb** [comment]
@PickRelated i agree :P
