### ISSUE TITLE
After packaging, the picture cannot be displayed

### ISSUE THREAD

**Issue by luchaoqun125** [vuejs/rollup-plugin-vue#348]
USE https://new-issue.vuejs.org/?repo=vuejs/rollup-plugin-vue

The development environment is normal
After packaging, the picture cannot be displayed

@rollup/plugin-url
rollup-plugin-vue

**Comment by znck** [comment]
Provide minimal reproduction code using JSFiddle/JSBin/Codepen/Github to demonstrate your issue.

Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. **The issue list only accepts bug reports and feature requests.**
