### ISSUE TITLE
Sorry but how to run this package ?

### ISSUE THREAD

**Issue by DrMabuse23** [vuejs/rollup-plugin-vue#349]
USE https://new-issue.vuejs.org/?repo=vuejs/rollup-plugin-vue
Hi thx for your Package,

but iam not sure how to run this script ? i`m using at the moment the vue-cli to create a web-component output. 
`vue-cli-service build --target wc --name <%=name%>`
and now how to use this plugin then ? i need to add rollup ? or this hook into the vue cli build ?
Sorry for my stupid questions but i dont see any on the docs how to run a build with that

**Comment by znck** [comment]
You can refer to [this article](https://znck.dev/blog/2019-shipping-web-components-with-vue).
