### ISSUE TITLE
NPM-Package should still deliver version 5

### ISSUE THREAD

**Issue by awaigand** [vuejs/rollup-plugin-vue#363]
### What problem does this feature solve?
Hi,
just a quick heads up, the npm package (rollup-plugin-vue) automatically installs version 6, which needs Vue 3.
I don't know if this was intended or is not your responsibility, but it just cost me about 30 mins to figure that out.

Best wishes

### What does the proposed API look like?
npm install rollup-plugin-vue

**Comment by subdavis** [comment]
Some search terms for other people who get bit by this:

* Error: rollup-plugin-vue requires @vue/compiler-sfc to be present in the dependency tree.
* vue-template-compiler
* `pushScopeId`, `resolveComponent`, `createVNode`, `createBlock`, `withCtx`, `withScopeId`, `withKeys` was not found in vue.

**Comment by znck** [comment]
This was not intended but eventually, v6 will become `latest` so it's better if you lock rollup-plugin-vue to `5.*` in you `package.json`.
