### ISSUE TITLE
Components cannot be found

### ISSUE THREAD

**Issue by mjmnagy** [vuejs/rollup-plugin-vue#383]
### Version
5.0.0

### Reproduction link
[https://github.com/mjmnagy/rollup-error-2020-08-27](https://github.com/mjmnagy/rollup-error-2020-08-27)

### Steps to reproduce
npm run prod

### What is expected?
create the rollup documents

### What is actually happening?
./components/index.js → dist/ulibrary.esm.js...
[!] Error: Could not load /Apps/icon/components/icon (imported by components\index.js): EISDIR: illegal operation on a directory, read
Error: Could not load /Apps/icon/components/icon (imported by components\index.js): EISDIR: illegal operation on a directory, read

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! icon@0.0.0 rollup: `rollup -c --environment BUILD:production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the icon@0.0.0 rollup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\..

---
- I have played with using different variations from the current alias to relavitive paths
https://rollup-plugin-vue.vuejs.org/options.html#template
https://github.com/vuejs/rollup-plugin-vue/tree/master/cookbook/library

**Comment by pearofducks** [comment]
@mjmnagy - This is not a problem with this plugin.

This plugin isn't even involved in the error stack that you've referenced. Rollup itself is telling you it can't find that file.

Files are found differently depending on which method is being used, Webpack, Rollup, Node, etc. - all might use different methods. You're relying on referencing a directory, and having Rollup know about that (and the `index.js` file inside). That's referred to as Node's resolution method - and Rollup has a plugin called `@rollup/plugin-node-resolve` for this.

---

As an error reproduction, this is really poor. I don't mean this in a "mean" way, just that maintainers do not have time to look at your entire project and dig into things. If you think you found an error, you need to strip away *all* your "project" stuff, and make the error happen with just a bare minimum of settings/modules.
