### ISSUE TITLE
Will this plugin support vue 3 ?

### ISSUE THREAD

**Issue by yaquawa** [vuejs/rollup-plugin-vue#393]
### What problem does this feature solve?
Vue 3 has been released for a while.
Because I see this repo has not been updated for a long time, I'm wondering is there any plan to support vue 3 in the future ?
Thanks.

### What does the proposed API look like?
...

**Comment by Niputi** [comment]
you can see vue 3 version of this plugin at https://github.com/vuejs/rollup-plugin-vue/tree/next

**Comment by yaquawa** [comment]
@Niputi Thanks a lot!
