### ISSUE TITLE
Is v6 supposed to be released as latest on npm?

### ISSUE THREAD

**Issue by joeldenning** [vuejs/rollup-plugin-vue#398]
### Version

6.0.0-beta.10

### Reproduction link
N/A

### Steps to reproduce
`npm info rollup-plugin-vue`

### What is actually happening?
Is rollup-plugin-vue@6.0.0-beta.10 expected to be the latest release? When I run `npm info rollup-plugin-vue`, it lists 6.0.0-beta.10 as the latest dist-tag. But the master branch shows rollup-plugin-vue@5, and I cannot find find any release notes or changelogs for rollup-plugin-vue@6 anywhere (including the next branch).

**Comment by znck** [comment]
That's possibly a mistake. Reverting it.
