### ISSUE TITLE
[!] (plugin vue) TypeError: Cannot read property 'refSugar' of undefined

### ISSUE THREAD

**Issue by heart-er** [vuejs/rollup-plugin-vue#452]
### Version
"rollup-plugin-vue": "^6.0.0-beta.10",

### Reproduction link
none

### Steps to reproduce
rollup build throw error about this
![image](https://user-images.githubusercontent.com/24717511/130778607-a90b8868-2b6d-4b1f-9e37-38ca3865be1d.png)

### What is expected?
no error

### What is actually happening?
throw error

**Comment by LinusBorg** [comment]
Please provide more context - dependency versions (exact ones on disc), rollup config ...

**Comment by heart-er** [comment]
thanks. i used vite-plugin to solve problem

**Comment by wiseadme** [comment]
Hi! I faced with the same problem. Is there any solution?

**Comment by wiseadme** [comment]
> Hi! I faced with the same problem. Is there any solution?

Downgrading the version from Vue 3.2.2 to 3.1.0 solved this problem for me
