### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by macu** [vuejs/rollup-plugin-vue#65]
In package.json devDependencies I have:
```
"rollup-plugin-vue": "^2.2.21",
"vue": "^2.2.1",
```

When I run my gulp vueify task I get an error:
```
Vue packages version mismatch:

- vue@2.2.1
- vue-template-compiler@2.1.10
```

Please update dependencies to use vue-template-compiler v2.2.1.

**Comment by znck** [comment]
Fixed in [v2.3.0-beta.5](https://github.com/vuejs/rollup-plugin-vue/releases/tag/v2.3.0-beta.5).
