### ISSUE TITLE
Ensure directory before writing css

### ISSUE THREAD

**Issue by egoist** [vuejs/rollup-plugin-vue#68]
### Expected behavior

Works like a charm.

### Actual behavior

With option `css: 'dist/main.css'` it outputs: `Error: ENOENT: no such file or directory, open 'dist/main.css'`

**Comment by posva** [comment]
I usually create the directories myself when I have a rollup build 😆

**Comment by egoist** [comment]
@posva really? create `dist` folder? 😂

**Comment by posva** [comment]
Yeah, haha: https://github.com/posva/vue-plugin-template/blob/master/template/build/build.js#L17

**Comment by znck** [comment]
I'd add a check for that.
