### ISSUE TITLE
Support for Stylus

### ISSUE THREAD

**Issue by quimarche** [vuejs/rollup-plugin-vue#78]
The following Vue file:

<template lang="pug">
div
  h1 Test
</template>

<script>
  export default {
  }
</script>

<style lang="stylus">
h1
  color red
</style>

Throws the error:

(vue plugin) Cannot read property 'call' of undefined

Less & Sass working as expected.

**Comment by znck** [comment]
Stylus is not supported yet.

**Comment by quimarche** [comment]
Happy to help.  Can't find a contributors guide.

**Comment by znck** [comment]
Create `stylus.js` in `src/style` directory and register in `src/style/index.js` as others.

> https://github.com/vuejs/rollup-plugin-vue/blob/master/.github/CONTRIBUTING.md
> 😝  It should be moved to project root.
