### ISSUE TITLE
How do you enable sourcemaps for CSS?

### ISSUE THREAD

**Issue by Francisc** [vuejs/rollup-plugin-vue#92]
Hello,

How does one enable sourcemaps for CSS in v2.4.0?

**Comment by y-nk** [comment]
@znck is it possible to disable this automatic feature to include sourcemap for dev env ?

**Comment by znck** [comment]
In v4.7.2, you can do `needMap: false` (It would be dropped when source map issues are resolved).

**Comment by y-nk** [comment]
@znck thanks ! is there a documentation about this somewhere ?
