### ISSUE TITLE
Support TypeScript in <script> tags

### ISSUE THREAD

**Issue by fogzot** [vuejs/rollup-plugin-vue#99]
~~This is not a bug, but a feature request. If this is not the correct place then just redirect me and close this issue. :)~~

Given that rollup already supports TypeScript via one of two plugins, it would be nice for this plugin to allow something along the lines of:
```
<script lang="ts">
// typescript Vue component here.
</script>
```

**Comment by AllNamesRTaken** [comment]
This would be great. 
And also set the output to ES2015 to allow better tree shaking when importing into other projects.

**Comment by fogzot** [comment]
@AllNamesRTaken that was the reason behind my request, i.e., distribute a library of Vue components as ES6 modules. Right now the only way is to "webpack" the library into a single, bloated js file that makes very difficult to not duplicate all the depencies, Vue included.
